	<form class="smart-form" method="post" enctype="multipart/form-data" action="home">
		<div class="left">
			<div id="advanced" class="component">
				<div class="head">
					<h3>Advanced Options</h3>
				</div>
				
				<div class="body">
					<p class="single"><label for="nomunge">Minify Only:</label> <input type="checkbox" id="nomunge" name="nomunge" value="1" /></p>
					<p class="single"><label for="preserve-semi">Preserve Semicolons:</label> <input type="checkbox" id="preserve-semi" name="preserve-semi" value="1" /></p>
					<p class="single"><label for="disable-optimizations">Disable Optimizations:</label> <input type="checkbox" id="disable-optimizations" name="disable-optimizations" value="1" /></p>
					<p class="single"><label for="zipped">Zipped Version:</label> <input type="checkbox" id="zipped" name="zipped" value="1" /></p>
					<p class="single">
						<!-- AddThis Button BEGIN -->
						<script type="text/javascript">var addthis_pub="4a11f1a92b988ae7";</script>
						<a href="http://www.addthis.com/bookmark.php?v=20" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" onmouseout="addthis_close()" onclick="return addthis_sendto()"><img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/200/addthis_widget.js"></script><!-- AddThis Button END -->
					</p>
				</div>
			</div>
		</div>
		
		<div class="right">
			<div id="compressor" class="component">
				<ol id="hint-content" style="display: none">
					<li>Select the first file, this will probably be a base framework or library</li>
					<li>Select the second file, this might be further libraries or plugins</li>
					<li>Select the third file, this might be specific functionality or your application file</li>
					<li>Select other files as required</li>
			    </ol>
				<div class="head">
					<h3>Compressor</h3>
				</div>
				
				<div id="body">
					<div class="file">
				        <p class="row">
				            <label>
								<strong>File <span class="index">1</span></strong>
				            	<input type="file" name="upload[]" value="" />
								<a class="remove-field control" href="#remove">remove</a>
							</label>
				        </p>
				
				        <!-- further upload fields added here -->
				    </div>
				    
				</div>
				
				<div id="action">
			        <a id="add-file" class="control" href="#add-file">add another file</a>
			    </div>
				
			</div>
			
			<div id="meta-info">

				<p>
					<label for="name">Name for compressed file:</label>
					<input type="text" id="name" name="name" value="" maxlength="40" />
					<strong>.</strong> <input id="name-suffix" name="name-suffix" disabled="disabled" maxlength="3" />
				</p>
				<p style="display: none;">
					<label for="file-header">Header comment:</label>
					<textarea id="file-header" name="file-header" rows="5" cols="40" wrap="off">
/* 
Compressed from: [file list]
On: [date:time]
For licences see individual files
*/
</textarea>
				</p>
			</div>
			
			<p id="compress-action">
		        <input id="compress-button" type="submit" name="submit" value="compress" />
		    </p>
		    
		    <div id="output">
				<?php if($error): ?>
				<div id="error-message">
					<h3>Error Message:</h3>
					<p><?php echo $error; ?></p>
				</div>
				<?php endif ?>
		
		        <?php if($compressed_file): ?>
		
		        <div id="compressedFile">
		            <p class="hint">Right click and save file...</p>
		            <h3><?php echo 'Download file: ' . $compressed_file; ?></h3>
		            <?php if($zipped_file): ?><h3><?php echo 'Download zipped version: ' . $zipped_file; ?></h3> <?php endif ?>
		        </div>
		
		        <?php endif ?>
		    </div>
		    
		</div>
	</form>