<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>The Compressor - <?php echo $page_title; ?></title>
    <link rel="stylesheet" type="text/css" href="/assets/css/master.css" media="all" />
    <style type="text/css" media="all">
		.page-stats { padding-top: 10px; border-top: 1px solid #ddd; font-size: .83em }
	</style>
</head>
<body>
	<div id="container">
		<div id="header">
			<div id="logo">
				<img src="/assets/images/logo.png" width="311" height="57" alt="Logo" />
			</div>
		</div>
		
		<!-- Content -->
		<div id="content">
        
        <?php echo $content_for_layout; ?>
        
		</div>
		<!-- / - Content -->
		
		<div id="footer">
			<p class="yui-version">Using <a href="http://developer.yahoo.com/yui/compressor/" target="_blank">YUI Compressor 2.4.2</a><br />any problems visit The Compressor <a href="http://www.assembla.com/spaces/the-compressor/tickets">Issue Tracker</a></p>
			<p class="copyright">Powered by Simple Engine Framework<br />another <a href="http://www.silentworks.co.uk" target="_blank">Silent Works</a> <em>beta</em> development.</p>
		</div>
	</div>
	
<script src="/assets/js/jquery-1.2.6.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/js/general.js" type="text/javascript" charset="utf-8"></script>    

<!-- Google Analytics -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8785440-1");
pageTracker._trackPageview();
} catch(err) {}</script>
<!-- / - Google Analytics -->

</body>
</html>
